# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Validate-YAML

on:
  push:
    branches: [main, next-minor, next-patch]
  pull_request:
    branches: [main, next-minor, next-patch]

permissions:
  contents: read

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    env:
      REGISTRY_DIRECTORIES: calendar/standard data-type/standard enumeration/standard enumeration-set/standard month/standard structure/extension structure/standard uri/exid-types

    steps:
      - name: Checkout GEDCOM.io
        uses: actions/checkout@v4

      - name: Validate YAML
        run: yamllint . .github .github/workflows $REGISTRY_DIRECTORIES

      - name: Validate YAML against schema
        run: |
          for dir in $DIRECTORIES; do
            echo DIR: $dir
            for filename in "$dir"/*; do
              echo FILE: $filename
              python registry_tools/validator.py "$filename"
            done
          done
